### PR TITLE
Transfering project to CMake

### PR DESCRIPTION
**Pull request by ivanboika**
I decided to transfer our project to CMake because of default VS build system does not work properly

### CODE REVIEW

**Comment by Gorba41kD** [comment]
Everything looks great. You've done an excellent job.In some places git wants empty space at the end of file

**Comment by ivanboika** [comment]
> Everything looks great. You've done an excellent job.In some places git wants empty space at the end of file

Yea thanks, but that's not enough
I want to add libpq dependency in cmake and I'm still struggling with it

**Review by Gorba41kD — APPROVED** [review]

**Comment by ivanboika** [comment]
Also check this branch at your own. If it does not work and problem is around 'conan install', install another one conan via .exe, non pip

**Comment by Gorba41kD** [comment]
@ivanboika , Checked everything works

**Review by Gorba41kD — APPROVED** [review]

**Pull request merged**
